### PR TITLE
Sighash default support

### PR DESCRIPTION
**Pull request by sgliner-ledger**
Add support for SIGHASH_DEFAULT.
Closes: #40, #47

### CODE REVIEW

**Review by bigspider — APPROVED** [review]
Nice!
Only one nit: in `test_sign_psbt_taproot_1to2_sighash_all`, I'd add checks to make sure that the signature is 65 bytes and the last byte is indeed `0x01` (it's actually implied by the hardcoded sighash... but still good for documentation purposes imho).

**Comment by sgliner-ledger** [comment]
@bigspider I think those checks were already implemented in the test before I renamed it, and I did not remove it, so it should still be there :)

**Comment by bigspider** [comment]
> When do you plan to release this ? Waiting since June to do a taproot transaction

Sorry for the delay; I'm not sure we'll have a release just for this feature before the next big release that is planned for October.
I'm curious what software are you using that adds SIGHASH_DEFAULT to the psbt?

Sending taproot txs works on Ledger Live, and I think it also works with Sparrow Wallet (they added an option for using SIGHASH_ALL).

**Comment by oliverlj** [comment]
Thank you for your answer.

I'm using sparrow wallet with a personal full node. SIGHASH_DEFAULT is still the default in sparrow

image

Tx broadcasted successfully with SIGHASH_ALL.

I do not want to use Ledger Live according to the tos data collecting to manage my satoshis. And i want to use my personal full node.

**Comment by bigspider** [comment]
Thanks for the feedback! Great that you could work around it until we improve support in the next release.

Not supporting SIGHASH_DEFAULT earlier was an oversight on my side, as it's indeed the sane default choice.

**Pull request merged**
